routes:
    # userRegister:
    #     path: /users/register
    #     controller: UserController:register
    #     methods: [POST]
    # userLogin:
    #     path: /users/login
    #     controller: UserController:login
    #     methods: [POST]
    getAllUsers:
        path: /users/index/
        controller: UserController:index
        methods: [GET]